# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_post_set', through='post.PostLike', to='member.MyUser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='post'),
        ),
    ]
