# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20170228_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkvideos',
            old_name='myuser',
            new_name='user',
        ),
    ]
