# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20170228_0747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookmarkVideos',
            new_name='BookmarkVideo',
        ),
    ]
