# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20170228_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bookmark_videos',
            field=models.ManyToManyField(blank=True, related_name='bookmark_user_set', through='member.BookmarkVideo', to='video.Video'),
        ),
    ]
