# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_thumbnail_url'),
        ('member', '0009_auto_20170228_0926'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmarkvideo',
            unique_together=set([('user', 'video')]),
        ),
    ]
