# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20170209_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='teacher',
            new_name='instructor',
        ),
    ]
