# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0016_auto_20170209_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentee_set', to='person.Person', verbose_name='멘토'),
        ),
    ]
