# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_created=True)),
                ('username', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('following', models.ManyToManyField(to='member.MyUser')),
            ],
        ),
    ]
