# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170213_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='nickname',
            new_name='nick_name',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=200, unique=True, verbose_name='유저네임'),
        ),
    ]
