# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20170213_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='nick_name',
            new_name='nickname',
        ),
    ]
