# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20170213_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
