# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_myuser_img_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='img_profile',
            new_name='photo',
        ),
    ]
