# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20170221_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='photo',
            new_name='img_profile',
        ),
    ]
