# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20170226_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
